
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan 10 2026 12:25:06 IST (Jan 10 2026 06:55:06 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, out);
  input clk, rst;
  output [3:0] out;
  wire clk, rst;
  wire [3:0] out;
  wire n_82, n_84, n_89, n_90, n_95, n_97, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_110;
  wire n_111, n_112, n_113, n_114, n_117, n_132, n_137;
  dfnrq4 \out_reg[2] (.CP (clk), .D (n_103), .Q (out[2]));
  dfnrq4 \out_reg[3] (.CP (clk), .D (n_117), .Q (out[3]));
  dfnrq4 \out_reg[1] (.CP (clk), .D (n_95), .Q (out[1]));
  dfnrq4 \out_reg[0] (.CP (clk), .D (n_90), .Q (out[0]));
  nd02d1 g120(.A1 (out[0]), .A2 (out[1]), .ZN (n_82));
  inv0d2 g121(.I (out[2]), .ZN (n_84));
  nr02d0 g20(.A1 (n_89), .A2 (out[0]), .ZN (n_90));
  inv0d1 g1665(.I (rst), .ZN (n_89));
  inv0d1 g25(.I (n_99), .ZN (n_95));
  nd03d1 g37(.A1 (n_105), .A2 (n_97), .A3 (rst), .ZN (n_99));
  nd02d1 g39(.A1 (out[0]), .A2 (out[1]), .ZN (n_97));
  nd02d1 g66(.A1 (n_101), .A2 (n_102), .ZN (n_103));
  nd12d1 g67(.A1 (n_100), .A2 (n_82), .ZN (n_101));
  nd02d2 g69(.A1 (out[2]), .A2 (rst), .ZN (n_100));
  nd04d1 g68(.A1 (out[1]), .A2 (n_84), .A3 (out[0]), .A4 (rst), .ZN
       (n_102));
  nd12d1 g6(.A1 (out[1]), .A2 (n_104), .ZN (n_105));
  inv0d1 g7(.I (out[0]), .ZN (n_104));
  nd02d1 g167(.A1 (n_112), .A2 (n_137), .ZN (n_117));
  nd03d1 g168(.A1 (n_107), .A2 (n_110), .A3 (n_111), .ZN (n_112));
  inv0d1 g173(.I (n_106), .ZN (n_107));
  nd02d2 g174(.A1 (out[1]), .A2 (out[2]), .ZN (n_106));
  inv0d2 g175(.I (n_132), .ZN (n_110));
  inv0d1 g178(.I (out[3]), .ZN (n_111));
  nd03d2 g170(.A1 (out[2]), .A2 (out[1]), .A3 (out[0]), .ZN (n_113));
  nd02d1 g172(.A1 (out[3]), .A2 (rst), .ZN (n_114));
  nd12d2 g1676(.A1 (n_89), .A2 (out[0]), .ZN (n_132));
  nd12d1 g2(.A1 (n_114), .A2 (n_113), .ZN (n_137));
endmodule

